<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>form_form</name>
   <tag></tag>
   <elementGuidId>9b2c4848-3787-43da-92dd-a3b687f33e15</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>form</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//form</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>form</value>
      <webElementGuid>cb9d1b7b-d768-4182-8e1f-2b80a6abfe43</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-f47671a8f53cf561c6f1bd35a1e2c9e8</value>
      <webElementGuid>707aa388-665c-4928-b04a-d3781ec9779a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//form</value>
      <webElementGuid>9a5662c2-e992-4562-8c87-1d99913a93ae</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//form</value>
      <webElementGuid>4914d690-0bc3-43f6-800f-bc4b6286d03a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
